--****************************SIS GESTANTE*****************************

SELECT
  ID_CARGA, FE_RECEPCION, NU_REGISTROS_CARGADOS
  FROM PROCESO_MASIVO_UOP.TCCARGA_SIS_GESTANTE
ORDER BY ID_CARGA DESC;


SELECT
PNM.FECHA_NAC_DEL_MENOR, PNM.TIPO_DE_DOCUMENTO, PNM.DNI_DEL_MENOR, PNM.CUI_DEL_MENOR, PNM.CNV_DEL_MENOR,
PNM.*FROM PROCESO_MASIVO_UOP.TDCARGA_PADRON_NOMINAL PNM WHERE PNM.DNI_DEL_MENOR='94408331'
AND TO_DATE(FECHA_NAC_DEL_MENOR) > TO_DATE('01/01/2025','DD/MM/YYYY');

describe PROCESO_MASIVO_UOP.TDCARGA_PADRON_NOMINAL;

--****************************ENCONTRAR ESTABLECIMIENTO DE SALUD********************************************

SELECT 
s.C_NEWCOD,
s.C_DIRSALUD,
s.*
FROM JUNTOS.TDIRSALUD s;

describe JUNTOS.TDIRSALUD;

----------------------------------VERIFICACION DE GESTANTES EN EL SITC---------------------

SELECT

T1.IDHOGAR,
t1.CODESTADOHOGAR,
T2.SECMIEMBRO,
T2.EGRESADO,
T2.FLAG_INTER_EGRESADO,
T3.SECMOBJETIVO,
T3.SALUDGESTANTE,
T3.EDUCACION,
T4.IDPERSONA,
T4.DNI,
T4.NOMBRE,
T4.PAPELLIDO,

T4.SAPELLIDO,
T4.FNACIMIENTO,
-- AÑOS
T4.GENERO,

-- CRP EDU AFI

T6.SECCRP,
T6.CODGRADO,
T6.SECCION,
T6.CODMODULAR,
T6.FDESDE,
T6.CODMOTIVONOESTUDIO,
T6.NO_ARCHIVO,
T6.FLAGINTER_IIEE,
T6.ANIO_ESCOLAR,

-- CRP GESTANTE AFI
T5.SECCRP,
T5.NUMMESES,
T5.FPP,
NULL AS FPP_NEW,

T5.CODEESS,
T5.FDESDE,
T5.SECMOBJETIVO,
T5.CODUSUARIO,
T5.C_DIRSALUD,
T5.NO_ARCHIVO,
T5.NUMSEMANA,
T5.FLAGINTER_EESS,

-- CRP EGRESADO AFI
T7.SECCRP,
T7.SECMIEMBRO,
T7.NO_ARCHIVO,
T7.VIGENTE,
T7.FE_CREACION,
T7.FE_MODIFICACION,
T7.US_CREACION

FROM SITC.HOGARAFI T1
  JOIN SITC.MIEMBROAFI T2
    ON T1.IDHOGAR = T2.IDHOGAR
    AND T2.VIGENTE = 1
  JOIN SITC.MOBJETIVOAFI T3
    ON T2.SECMIEMBRO = T3.SECMIEMBRO
      AND T3.VIGENTE = 1
  JOIN SITC.PERSONA T4
    ON T2.IDPERSONA = T4.IDPERSONA
  JOIN SITC.CRPSALUDGESTANTEAFI T5
    ON T3.SECMOBJETIVO = T5.SECMOBJETIVO
      AND T5.VIGENTE = 1
   LEFT JOIN SITC.CRPEDUCACIONAFI T6
      ON T5.SECCRP = T6.SECCRP
    AND T6.VIGENTE = 1
    LEFT JOIN SITC.CRPEGRESADOAFI T7
       ON T6.SECCRP = T7.SECCRP
        AND T7.VIGENTE = 1
    WHERE T2.VIGENTE = 1
    AND T2.CODMOTIVORECHAZO IS NULL                                                                                           
    /*
    AND TRUNC(T1.F_REGISTRO_AFI) IN (
        TO_DATE('08/09/2025', 'DD/MM/YYYY')
    )

    */
    AND TRUNC(T1.F_REGISTRO_AFI) BETWEEN TO_DATE('01/01/2014', 'DD/MM/YYYY') AND TO_DATE('31/12/2025', 'DD/MM/YYYY')
    AND T1.CODESTADOHOGAR IN ( '13','14') -- 13 : Hogares elegibles | 14 : Hogares preafiliados
    ORDER BY T5.FPP ASC;
    
    --trabajar en esto
    SELECT*FROM SITC.CRPSALUDGESTANTEAFI;
    
    SELECT *FROM PROCESO_MASIVO_UOP.TDCARGA_SIS_GESTANTE;


---------------------------------------- 4. Consulta para observar el insumo de GESTANTES --------------------------------------------------
--PARA GESTANTES 

    SELECT *
    FROM SITC.TSIS_GEST
    WHERE DNI = '45637359';
    
    SELECT * FROM PROCESO_MASIVO_UOP.TCCARGA_SIS_GESTANTE WHERE DNI = '45637359';

--PARA RN

    SELECT * FROM PROCESO_MASIVO_UOP.TDCARGA_PADRON_NOMINAL
    where DNI_DE_LA_MADRE = '45637359';

    SELECT*FROM SITC.TPADRON_NOMINAL where DNI_DE_LA_MADRE = '45637359';

---------------------------------------- 5. Consulta para observar el detalle de GESTANTES --------------------------------------------------

SELECT
     ID,
    ID_CARGA,
    DNI,
    AP_PATERNO || ' ' || AP_MATERNO || ' ' || NOMBRES AS "NOMBRES COMPLETOS" ,
    FECHA_PROBABLE_PARTO,
  -- FECHA_NAC,
    ES_GESTANTE

FROM PROCESO_MASIVO_UOP.TDCARGA_SIS_GESTANTE WHERE DNI = '81155165';


----------------------------------------------------------VER ULTIMA CONSULTA DE LA GESTANTE------------------------------------
 
SELECT *
FROM PROCESO_MASIVO_UOP.TDCARGA_SIS_GESTANTE
WHERE dni = '77496918'
ORDER BY TO_DATE(FECHA_ATENCION, 'DD-MON-YY', 'NLS_DATE_LANGUAGE = ENGLISH') DESC;

--------------------------------VER ULTIMSA CONSULTAS DE UN GRUPO DE GESTANTES------------------------------------------------
SELECT 
    ID,
    ID_CARGA,
    DNI,
    NOMBRES || ' ' || AP_PATERNO || ' ' || AP_MATERNO AS "NOMBRES COMPLETOS",
    FECHA_PROBABLE_PARTO,
    ES_GESTANTE
FROM (
    SELECT 
        t.*,
        ROW_NUMBER() OVER (PARTITION BY DNI ORDER BY ID DESC) AS rn
    FROM PROCESO_MASIVO_UOP.TDCARGA_SIS_GESTANTE t
    WHERE DNI IN ('90968793',
'91986744',
'91570849',
'81639747'
    )
)
WHERE rn = 1 AND FECHA_PROBABLE_PARTO > '01-OCT-2025';

---------------------------------------------------VERIFICAR EN EL PADRON NOMINAL CON EL DNI DE LA MADRE------------------------------

SELECT
PN.FECHA_NAC_DEL_MENOR, PN.TIPO_DE_DOCUMENTO,PN.DNI_DEL_MENOR, PN.CUI_DEL_MENOR, PN.CNV_DEL_MENOR,PN.*
FROM SITC.TPADRON_NOMINAL PN
WHERE DNI_DE_LA_MADRE = '46326857' AND  TO_DATE(FECHA_NAC_DEL_MENOR) > TO_DATE('01/01/2025','DD/MM/YYYY')
ORDER BY FE_MODI_REGISTRO  DESC;

SELECT
PNM.FECHA_NAC_DEL_MENOR, PNM.TIPO_DE_DOCUMENTO, PNM.DNI_DEL_MENOR, PNM.CUI_DEL_MENOR, PNM.CNV_DEL_MENOR,
PNM.*FROM PROCESO_MASIVO_UOP.TDCARGA_PADRON_NOMINAL PNM WHERE PNM.DNI_DE_LA_MADRE='46326857'
AND TO_DATE(FECHA_NAC_DEL_MENOR) > TO_DATE('01/01/2025','DD/MM/YYYY');


SELECT*FROM PROCESO_MASIVO_UOP.TDCARGA_SIS_GESTANTE WHERE NU_DOCUMENTO='44266666';

 SELECT*FROM sitc.CRPSALUDGESTANTEAFI WHERE SECMOBJETIVO='21698126';
 
--------------------------------------------------INTEGRANTE GESTANTE CON SEXO MASCULINO-------------------------------------------------

SELECT t0.idhogAR,
        t0.codestadohogar,
        T0.FELEGIBILIDAD,
        T0.MODALIDAD_INGRESO,
        t1.secmiembro,
        t2.secmobjetivo,
        t3.*,
        t4.*
FROM SITC.HOGARAFI T0
JOIN SITC.MIEMBROAFI T1
    ON T0.IDHOGAR=T1.IDHOGAR
        AND T1.VIGENTE='1'
LEFT
JOIN SITC.MOBJETIVOAFI T2
    ON T2.SECMIEMBRO=T1.SECMIEMBRO
        AND T2.VIGENTE='1'
LEFT
JOIN SITC.CRPSALUDGESTANTEAFI T3
    ON T3.SECMOBJETIVO=T2.SECMOBJETIVO
        AND T3.VIGENTE='1'
JOIN SITC.PERSONA T4
    ON T4.IDPERSONA=T1.IDPERSONA
WHERE T0.CODESTADOHOGAR IN ('13','14')
        AND T4.GENERO='M'
        AND T2.SALUDGESTANTE='1';


---------------------------------------------------INTEGRANTE GESTANTE MENOR DE 15 AÑOS---------------------------------------------

SELECT t0.idhogAR,
        T0.CODESTADOHOGAR,
        T0.F_REGISTRO_AFI,
        T0.FELEGIBILIDAD,
        T0.MODALIDAD_INGRESO,
        
t1.secmiembro,
        t2.secmobjetivo,
        t2.saludgestante,
        t3.*,
        TRUNC(MONTHS_BETWEEN(SYSDATE,
        (T4.FNACIMIENTO))/12) AS EDAD_ANIO,
        t4.*
FROM SITC.HOGARAFI T0
JOIN SITC.MIEMBROAFI T1
    ON T0.IDHOGAR=T1.IDHOGAR
        AND T1.VIGENTE='1'
LEFT
JOIN SITC.MOBJETIVOAFI T2
    ON T2.SECMIEMBRO=T1.SECMIEMBRO
        AND T2.VIGENTE='1'
LEFT
JOIN SITC.CRPSALUDGESTANTEAFI T3
    ON T3.SECMOBJETIVO=T2.SECMOBJETIVO
        AND T3.VIGENTE='1'
JOIN SITC.PERSONA T4
    ON T4.IDPERSONA=T1.IDPERSONA
WHERE T0.CODESTADOHOGAR IN ('13','14')
        AND TRUNC(MONTHS_BETWEEN(SYSDATE,(T4.FNACIMIENTO))/12)<10
        AND T2.SALUDGESTANTE='1';


-------------------------------------------------INTEGRANTE GESTANTE MAYOR DE 55 AÑOS------------------------------------------------
SELECT 
t0.idhogAR,
T0.CODESTADOHOGAR,     
T0.F_REGISTRO_AFI,       
T0.FELEGIBILIDAD,       
T0.MODALIDAD_INGRESO,      
t1.secmiembro,      
t2.secmobjetivo,     
t3.*,
        
TRUNC(MONTHS_BETWEEN(SYSDATE,
        (T4.FNACIMIENTO))/12) AS EDAD_ANIO,
        t4.*
FROM SITC.HOGARAFI T0
JOIN SITC.MIEMBROAFI T1
    ON T0.IDHOGAR=T1.IDHOGAR
        AND T1.VIGENTE='1'
LEFT
JOIN SITC.MOBJETIVOAFI T2
    ON T2.SECMIEMBRO=T1.SECMIEMBRO
        AND T2.VIGENTE='1'
LEFT
JOIN SITC.CRPSALUDGESTANTEAFI T3
    ON T3.SECMOBJETIVO=T2.SECMOBJETIVO
        AND T3.VIGENTE='1'
JOIN SITC.PERSONA T4
    ON T4.IDPERSONA=T1.IDPERSONA
WHERE T0.CODESTADOHOGAR IN ('13','14')
        AND TRUNC(MONTHS_BETWEEN(SYSDATE,(T4.FNACIMIENTO))/12)>55
        AND T2.SALUDGESTANTE='1';


-------------------------CAMBIAR ESTADO GESTANTE EN NIÑAS-ADULTAS MAYORES || VERIFICAR SI EN SALUD GESTANTE Y VIGENTE ESTÁ EN 1 A TRAVEZ DE SECMOBJETIVO------------------------

/*EN EL APARTADO DE MO*/
SELECT
t3.IDHOGAR,
t5.ORIGEN_HE,
t3.IDPERSONA,
T1.SECMIEMBRO,
T1.SECMOBJETIVO,
t4.DNI,
t4.papellido || ' ' || t4.sapellido || ' ' ||t4.nombre as MO,
t4.FNACIMIENTO,
TRUNC(MONTHS_BETWEEN(SYSDATE,t4.FNACIMIENTO)/12)EDAD,
t4.GENERO,
T1.SECMOBJETIVO,
T1.CODESTADOMO,
T1.EDUCACION,
T1.SALUD,
T1.SALUDGESTANTE,
null as SALUD_NEW,
null as SALUDGESTANTE_NEW
FROM
sitc.mobjetivoafi T1
JOIN SITC.MIEMBROAFI T3 on t1.secmiembro=T3.SECMIEMBRO
join sitc.hogarafi t5 on t3.idhogar = t5.IDHOGAR
JOIN SITC.PERSONA T4 on t3.idpersona=T4.IDPERSONA
JOIN sitc.crpsaludgestanteafi T2
ON T1.SECMOBJETIVO = T2.SECMOBJETIVO and t2.vigente='1'
WHERE T1.SECMOBJETIVO in ( 
'21711100',
'21712857',
'21760062',
'21698169',
'21700103') and t1.vigente='1'
;

/*EN CRPSALUDGESTANTE*/
SELECT
t3.IDHOGAR,
t5.ORIGEN_HE,
t3.IDPERSONA,
T1.SECMIEMBRO,
T1.SECMOBJETIVO,
t4.DNI,
t4.papellido || ' ' || t4.sapellido || ' ' ||t4.nombre as MO,
t4.FNACIMIENTO,
TRUNC(MONTHS_BETWEEN(SYSDATE,t4.FNACIMIENTO)/12)EDAD,
t4.GENERO,
T1.SECMOBJETIVO,
T2.SECCRP,
T2.NUMMESES,
T2.FPP,
T2.CODEESS,
T2.VIGENTE,
NULL AS VIGENTE_NEW

FROM
sitc.mobjetivoafi T1
JOIN SITC.MIEMBROAFI T3 on t1.secmiembro=T3.SECMIEMBRO
join sitc.hogarafi t5 on t3.idhogar = t5.IDHOGAR
JOIN SITC.PERSONA T4 on t3.idpersona=T4.IDPERSONA
JOIN sitc.crpsaludgestanteafi T2
ON T1.SECMOBJETIVO = T2.SECMOBJETIVO and t2.vigente='1'
WHERE T1.SECMOBJETIVO in ( 
'21711100',
'21712857',
'21760062',
'21698169',
'21700103') and t1.vigente='1'
;

------------------------NOMINA PARA EL REUSO IDPERSONA EN GESTANTE QUE TIENEN OTRO NOMBRE (EN SU MAYORIA DE HOMBRE) Y GENERO "M"-------------------------------------

SELECT 
    T0.IDHOGAR,
    T4.IDPERSONA,
    T1.SECMIEMBRO,
    T4.CODTIPODOCUMENTO,
    T4.DNI,	
    T4.NOMBRE,	
    T4.PAPELLIDO,	
    T4.SAPELLIDO,
    NULL AS NOMBRE_NEW,
    NULL AS PAPELLIDO_NEW,
    NULL AS SAPELLIDO_NEW,
    T4.FNACIMIENTO,
    NULL AS FNACIMIENTO_NEW,
    T4.GENERO,
    NULL AS GENERO_NEW
FROM SITC.HOGARAFI T0
JOIN SITC.MIEMBROAFI T1 
    ON T0.IDHOGAR = T1.IDHOGAR AND T1.VIGENTE = '1'
LEFT JOIN SITC.MOBJETIVOAFI T2 
    ON T2.SECMIEMBRO = T1.SECMIEMBRO AND T2.VIGENTE = '1'
LEFT JOIN SITC.CRPSALUDGESTANTEAFI T3 
    ON T3.SECMOBJETIVO = T2.SECMOBJETIVO AND T3.VIGENTE = '1'
JOIN SITC.PERSONA T4 
    ON T4.IDPERSONA = T1.IDPERSONA
WHERE 
    T0.CODESTADOHOGAR IN ('13','14') 
    AND T2.SALUDGESTANTE = '1'
    AND T4.DNI='76816257';

----------------------------------------------------NOMINA PARA CAMBIAR SOLO EL GENERO "M" EN GESTANTE----------------------------------------
SELECT 
    T0.IDHOGAR,
    T4.IDPERSONA,
    T1.SECMIEMBRO,
    T4.CODTIPODOCUMENTO,
    T4.DNI,	
    T4.NOMBRE,	
    T4.PAPELLIDO,	
    T4.SAPELLIDO,
    T4.GENERO,
    NULL AS GENERO_NEW
FROM SITC.HOGARAFI T0
JOIN SITC.MIEMBROAFI T1 
    ON T0.IDHOGAR = T1.IDHOGAR AND T1.VIGENTE = '1'
LEFT JOIN SITC.MOBJETIVOAFI T2 
    ON T2.SECMIEMBRO = T1.SECMIEMBRO AND T2.VIGENTE = '1'
LEFT JOIN SITC.CRPSALUDGESTANTEAFI T3 
    ON T3.SECMOBJETIVO = T2.SECMOBJETIVO AND T3.VIGENTE = '1'
JOIN SITC.PERSONA T4 
    ON T4.IDPERSONA = T1.IDPERSONA
WHERE 
    T0.CODESTADOHOGAR IN ('13','14') 
    AND T2.SALUDGESTANTE = '1'
    AND T4.DNI='45108522';
